apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-servicemonitor
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: postgres
  endpoints:
    - port: http
      interval: 15s